/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Cliente: () => import('#controllers/cliente_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Producto: () => import('#controllers/producto_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Role: () => import('#controllers/role_controller'),
  User: () => import('#controllers/user_controller'),
  Venta: () => import('#controllers/venta_controller'),
}
