/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BitacoraSchema extends BaseModel {
  static $columns = ['accion', 'createdAt', 'descripcion', 'id', 'ip', 'registroId', 'tabla', 'userAgent', 'usuarioId'] as const
  $columns = BitacoraSchema.$columns
  @column()
  declare accion: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string | null
  @column()
  declare registroId: number | null
  @column()
  declare tabla: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare usuarioId: number | null
}

export class CarritoSchema extends BaseModel {
  static $columns = ['cantidad', 'clienteId', 'createdAt', 'id', 'productoId', 'updatedAt'] as const
  $columns = CarritoSchema.$columns
  @column()
  declare cantidad: number
  @column()
  declare clienteId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategoriaSchema extends BaseModel {
  static $columns = ['activo', 'color', 'createdAt', 'descripcion', 'icono', 'id', 'nombre', 'updatedAt'] as const
  $columns = CategoriaSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column()
  declare icono: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ClienteSchema extends BaseModel {
  static $columns = ['activo', 'apellido', 'ciudad', 'codigoPostal', 'createdAt', 'direccion', 'email', 'estado', 'fechaNacimiento', 'foto', 'genero', 'id', 'nivel', 'nombre', 'pais', 'puntos', 'rfc', 'telefono', 'updatedAt', 'usuarioId'] as const
  $columns = ClienteSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare apellido: string
  @column()
  declare ciudad: string | null
  @column()
  declare codigoPostal: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare direccion: string | null
  @column()
  declare email: string
  @column()
  declare estado: string | null
  @column.date()
  declare fechaNacimiento: DateTime | null
  @column()
  declare foto: string | null
  @column()
  declare genero: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nivel: string | null
  @column()
  declare nombre: string
  @column()
  declare pais: string | null
  @column()
  declare puntos: number | null
  @column()
  declare rfc: string | null
  @column()
  declare telefono: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usuarioId: number | null
}

export class CompraSchema extends BaseModel {
  static $columns = ['createdAt', 'estado', 'fechaEntrega', 'folio', 'id', 'iva', 'notas', 'proveedorId', 'subtotal', 'sucursalId', 'total', 'updatedAt', 'usuarioId'] as const
  $columns = CompraSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estado: string | null
  @column.dateTime()
  declare fechaEntrega: DateTime | null
  @column()
  declare folio: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iva: string
  @column()
  declare notas: string | null
  @column()
  declare proveedorId: number
  @column()
  declare subtotal: string
  @column()
  declare sucursalId: number
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usuarioId: number
}

export class ConfiguracionSchema extends BaseModel {
  static $columns = ['clave', 'createdAt', 'descripcion', 'grupo', 'id', 'updatedAt', 'valor'] as const
  $columns = ConfiguracionSchema.$columns
  @column()
  declare clave: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column()
  declare grupo: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare valor: string | null
}

export class DetalleCompraSchema extends BaseModel {
  static $columns = ['cantidad', 'compraId', 'createdAt', 'id', 'precioUnitario', 'productoId', 'total', 'updatedAt'] as const
  $columns = DetalleCompraSchema.$columns
  @column()
  declare cantidad: number
  @column()
  declare compraId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare precioUnitario: string
  @column()
  declare productoId: number
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DetalleVentaSchema extends BaseModel {
  static $columns = ['cantidad', 'createdAt', 'descuentoUnitario', 'id', 'precioUnitario', 'productoId', 'total', 'updatedAt', 'ventaId'] as const
  $columns = DetalleVentaSchema.$columns
  @column()
  declare cantidad: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descuentoUnitario: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare precioUnitario: string
  @column()
  declare productoId: number
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare ventaId: number
}

export class FavoritoSchema extends BaseModel {
  static $columns = ['clienteId', 'createdAt', 'id', 'productoId', 'updatedAt'] as const
  $columns = FavoritoSchema.$columns
  @column()
  declare clienteId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HistorialMovimientoSchema extends BaseModel {
  static $columns = ['createdAt', 'datosAnteriores', 'datosNuevos', 'id', 'ip', 'productoId', 'registroId', 'tablaAfectada', 'tipoMovimiento', 'userAgent', 'usuarioId'] as const
  $columns = HistorialMovimientoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare datosAnteriores: string | null
  @column()
  declare datosNuevos: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string | null
  @column()
  declare productoId: number | null
  @column()
  declare registroId: number | null
  @column()
  declare tablaAfectada: string | null
  @column()
  declare tipoMovimiento: string
  @column()
  declare userAgent: string | null
  @column()
  declare usuarioId: number
}

export class ImagenesProductoSchema extends BaseModel {
  static $columns = ['createdAt', 'esPrincipal', 'id', 'imagenUrl', 'orden', 'productoId', 'updatedAt'] as const
  $columns = ImagenesProductoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare esPrincipal: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagenUrl: string
  @column()
  declare orden: number | null
  @column()
  declare productoId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InventarioSchema extends BaseModel {
  static $columns = ['cantidad', 'createdAt', 'fechaVencimiento', 'id', 'lote', 'productoId', 'stockMaximo', 'stockMinimo', 'sucursalId', 'ubicacion', 'updatedAt'] as const
  $columns = InventarioSchema.$columns
  @column()
  declare cantidad: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare fechaVencimiento: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lote: string | null
  @column()
  declare productoId: number
  @column()
  declare stockMaximo: number | null
  @column()
  declare stockMinimo: number | null
  @column()
  declare sucursalId: number
  @column()
  declare ubicacion: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MarcaSchema extends BaseModel {
  static $columns = ['activo', 'createdAt', 'descripcion', 'id', 'logo', 'nombre', 'sitioWeb', 'updatedAt'] as const
  $columns = MarcaSchema.$columns
  @column()
  declare activo: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare logo: string | null
  @column()
  declare nombre: string
  @column()
  declare sitioWeb: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MetodosPagoSchema extends BaseModel {
  static $columns = ['activo', 'createdAt', 'descripcion', 'id', 'nombre', 'updatedAt'] as const
  $columns = MetodosPagoSchema.$columns
  @column()
  declare activo: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProductoSchema extends BaseModel {
  static $columns = ['activo', 'categoriaId', 'codigo', 'createdAt', 'descripcion', 'destacado', 'dimensiones', 'especificaciones', 'garantiaMeses', 'id', 'marcaId', 'nombre', 'peso', 'precioCompra', 'precioOferta', 'precioVenta', 'stockMaximo', 'stockMinimo', 'updatedAt'] as const
  $columns = ProductoSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare categoriaId: number
  @column()
  declare codigo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column()
  declare destacado: boolean | null
  @column()
  declare dimensiones: string | null
  @column()
  declare especificaciones: string | null
  @column()
  declare garantiaMeses: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare marcaId: number
  @column()
  declare nombre: string
  @column()
  declare peso: string | null
  @column()
  declare precioCompra: string
  @column()
  declare precioOferta: string | null
  @column()
  declare precioVenta: string
  @column()
  declare stockMaximo: number
  @column()
  declare stockMinimo: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ProveedoreSchema extends BaseModel {
  static $columns = ['activo', 'ciudad', 'codigoPostal', 'contactoEmail', 'contactoNombre', 'contactoTelefono', 'createdAt', 'direccion', 'email', 'estado', 'id', 'nombre', 'pais', 'rfc', 'telefono', 'updatedAt'] as const
  $columns = ProveedoreSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare ciudad: string | null
  @column()
  declare codigoPostal: string | null
  @column()
  declare contactoEmail: string | null
  @column()
  declare contactoNombre: string | null
  @column()
  declare contactoTelefono: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare direccion: string | null
  @column()
  declare email: string | null
  @column()
  declare estado: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column()
  declare pais: string | null
  @column()
  declare rfc: string | null
  @column()
  declare telefono: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'descripcion', 'id', 'nombre', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descripcion: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SucursaleSchema extends BaseModel {
  static $columns = ['activo', 'ciudad', 'codigoPostal', 'createdAt', 'direccion', 'email', 'estado', 'horarioAtencion', 'id', 'latitud', 'longitud', 'nombre', 'pais', 'telefono', 'updatedAt'] as const
  $columns = SucursaleSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare ciudad: string
  @column()
  declare codigoPostal: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare direccion: string
  @column()
  declare email: string | null
  @column()
  declare estado: string
  @column()
  declare horarioAtencion: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitud: string | null
  @column()
  declare longitud: string | null
  @column()
  declare nombre: string
  @column()
  declare pais: string | null
  @column()
  declare telefono: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UsuarioSchema extends BaseModel {
  static $columns = ['activo', 'apellido', 'createdAt', 'email', 'fotoPerfil', 'id', 'nombre', 'password', 'rememberToken', 'rolId', 'telefono', 'ultimoLogin', 'updatedAt'] as const
  $columns = UsuarioSchema.$columns
  @column()
  declare activo: boolean | null
  @column()
  declare apellido: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fotoPerfil: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare rememberToken: string | null
  @column()
  declare rolId: number
  @column()
  declare telefono: string | null
  @column.dateTime()
  declare ultimoLogin: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VentaSchema extends BaseModel {
  static $columns = ['clienteId', 'createdAt', 'descuento', 'estado', 'fechaPago', 'folio', 'id', 'iva', 'metodoPagoId', 'notas', 'subtotal', 'sucursalId', 'total', 'updatedAt', 'usuarioId'] as const
  $columns = VentaSchema.$columns
  @column()
  declare clienteId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descuento: string | null
  @column()
  declare estado: string | null
  @column.dateTime()
  declare fechaPago: DateTime | null
  @column()
  declare folio: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare iva: string
  @column()
  declare metodoPagoId: number
  @column()
  declare notas: string | null
  @column()
  declare subtotal: string
  @column()
  declare sucursalId: number
  @column()
  declare total: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare usuarioId: number
}
